version: '3.4'

services:
  api:
    container_name: express-ts-server
    build:
      context: .
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - PORT=3000
    volumes:
      - ./src:/usr/app/src
